# This file acts as the base configuration file for the project.
# See configs/template.yaml for an example how to create a deviating configuration file
# By default the config/user.yaml configuration file is used.

# used for logging
project_name: "template"

# used for naming purposes
note: "note"

robot_parameters:
  verbose: False

# device on which to train
device: "cuda"

pre_scanned_graphs:
  base_fiducial_id: 52
  graph_frame_name_prefix: "filtered_fiducial_"
  floor: -0.1
  low_res: "24-03-26"
  high_res: "24-03-27b"
  masked: ""

# paths are relative from project_root_directory
subpaths:
  cache: "cache/"
  logs: "resources/logs/"
  output: "output/"
  resources: "resources/"
  graphs: "resources/graphs/"
  prescans: "resources/prescans"
  autowalks: "resources/autowalk"
  point_clouds: "resources/point_clouds"
  aligned_point_clouds: "resources/aligned_point_clouds"
  masks: "resources/masked"
  # environment
  environment: ".environment.yaml"
  spot_description: "spot_description"
  tmp: "resources/tmp"
  openmask_features: "resources/openmask_features"

servers:
  graspnet:
    ip: "127.0.0.1"
    port: 5000
    route: "graspnet/predict"
  openmask:
    ip: "127.0.0.1"
    port: 5001
    route: "openmask/save_and_predict"
  vitpose:
    ip: "127.0.0.1"
    port: 5002
    route: "vitpose/predict"
  darknet:
    ip: "127.0.0.1"
    port: 5003
    route: "darknet/predict"
  yolodrawer:
    ip: "127.0.0.1"
    port: 5004
    route: "yolodrawer/predict"